# Generated by Django 6.0.5 on 2026-05-23 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên khóa học")),
                (
                    "university",
                    models.CharField(max_length=255, verbose_name="Trường đại học"),
                ),
                (
                    "difficulty_level",
                    models.CharField(max_length=50, verbose_name="Cấp độ khó"),
                ),
                (
                    "url",
                    models.URLField(max_length=500, verbose_name="Đường dẫn khóa học"),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả ngắn"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả chi tiết"
                    ),
                ),
            ],
            options={
                "verbose_name": "Khóa học",
                "verbose_name_plural": "Danh sách Khóa học",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Số sao đánh giá")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Bình luận"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày đánh giá"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.course",
                        verbose_name="Khóa học",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Danh sách Đánh giá",
            },
        ),
        migrations.CreateModel(
            name="CourseView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=1, verbose_name="Số lượt xem"),
                ),
                (
                    "last_viewed",
                    models.DateTimeField(auto_now=True, verbose_name="Lần cuối xem"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_views",
                        to="courses.course",
                        verbose_name="Khóa học",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lượt xem khóa học",
                "verbose_name_plural": "Theo dõi Lượt xem",
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_enrolled",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày đăng ký"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Progress", "Đang học"),
                            ("Completed", "Đã hoàn thành"),
                        ],
                        default="In Progress",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="Khóa học",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lượt đăng ký",
                "verbose_name_plural": "Danh sách Đăng ký học",
                "unique_together": {("user", "course")},
            },
        ),
    ]
